---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-demo
  namespace: argocd
  labels:
    app.kubernetes.io/name: api-demo
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/ngrok-samples/gitops
    targetRevision: HEAD
    path: apps/api-demo
  destination:
    server: https://kubernetes.default.svc
    namespace: api-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
