---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ngrok-operator
  namespace: argocd
  labels:
    app.kubernetes.io/name: ngrok-operator
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://charts.ngrok.com
    chart: ngrok-operator
    targetRevision: 0.19.0
    helm:
      values: |
        credentials:
          secret:
            create: false
            name: ngrok-operator-credentials
  destination:
    server: https://kubernetes.default.svc
    namespace: ngrok-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
