---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-demo
  namespace: api-demo
  labels:
    app: api-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-demo
  template:
    metadata:
      labels:
        app: api-demo
    spec:
      containers:
      - name: api-demo
        image: joelatngrok/api-demo:latest
        ports:
        - containerPort: 4000
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: api-demo-service
  namespace: api-demo
  labels:
    app: api-demo
spec:
  selector:
    app: api-demo
  ports:
  - port: 4000
    targetPort: 4000
    protocol: TCP
  type: ClusterIP
